import type { Visibility } from "../src/lib/constants";

export interface SeedRecipe {
  title: string;
  description: string;
  ingredients: { name: string; quantity: string }[];
  instructions: string;
  calories: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  servings: number;
  prepMinutes: number;
  tags: string[];
  visibility: Visibility;
  author: "demo" | "alex";
}

export const RECIPES: SeedRecipe[] = [
  {
    title: "High-Protein Overnight Oats",
    description: "Prep it the night before for a grab-and-go breakfast that hits your protein target.",
    ingredients: [
      { name: "Rolled oats", quantity: "60 g" },
      { name: "Milk (or plant milk)", quantity: "200 ml" },
      { name: "Vanilla whey protein", quantity: "1 scoop" },
      { name: "Greek yogurt", quantity: "100 g" },
      { name: "Chia seeds", quantity: "1 tbsp" },
      { name: "Honey", quantity: "1 tsp" },
    ],
    instructions:
      "Mix all ingredients in a jar until the protein powder is fully combined. Cover and refrigerate overnight. Stir and top with fruit before eating.",
    calories: 420,
    proteinG: 32,
    carbsG: 48,
    fatG: 12,
    servings: 1,
    prepMinutes: 5,
    tags: ["breakfast", "high-protein", "meal-prep"],
    visibility: "PUBLIC",
    author: "demo",
  },
  {
    title: "Grilled Chicken & Rice Bowl",
    description: "The classic bodybuilding meal-prep staple — simple, balanced, and easy to batch cook.",
    ingredients: [
      { name: "Chicken breast", quantity: "200 g" },
      { name: "Cooked jasmine rice", quantity: "200 g" },
      { name: "Broccoli", quantity: "150 g" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Garlic powder, salt, pepper", quantity: "to taste" },
    ],
    instructions:
      "Season and grill the chicken breast 5-6 minutes per side until cooked through. Steam the broccoli. Plate over rice and drizzle with olive oil.",
    calories: 550,
    proteinG: 45,
    carbsG: 55,
    fatG: 14,
    servings: 1,
    prepMinutes: 25,
    tags: ["lunch", "high-protein", "meal-prep"],
    visibility: "PUBLIC",
    author: "demo",
  },
  {
    title: "Post-Workout Protein Smoothie",
    description: "Fast-digesting carbs and protein to kickstart recovery right after training.",
    ingredients: [
      { name: "Banana", quantity: "1" },
      { name: "Whey protein", quantity: "1 scoop" },
      { name: "Milk", quantity: "250 ml" },
      { name: "Ice", quantity: "1 cup" },
      { name: "Honey", quantity: "1 tsp" },
    ],
    instructions: "Blend everything until smooth. Drink within 30-45 minutes of finishing your session.",
    calories: 320,
    proteinG: 30,
    carbsG: 40,
    fatG: 6,
    servings: 1,
    prepMinutes: 5,
    tags: ["post-workout", "high-protein", "quick"],
    visibility: "FRIENDS",
    author: "demo",
  },
  {
    title: "Salmon with Roasted Vegetables",
    description: "Omega-3-rich dinner that still comes in with a serious protein hit.",
    ingredients: [
      { name: "Salmon fillet", quantity: "180 g" },
      { name: "Asparagus", quantity: "150 g" },
      { name: "Cherry tomatoes", quantity: "100 g" },
      { name: "Olive oil", quantity: "1 tbsp" },
      { name: "Lemon", quantity: "1/2" },
    ],
    instructions:
      "Roast vegetables at 200°C for 15 minutes. Add salmon, drizzle with oil and lemon, and roast a further 12-15 minutes until flaky.",
    calories: 480,
    proteinG: 38,
    carbsG: 20,
    fatG: 26,
    servings: 1,
    prepMinutes: 30,
    tags: ["dinner", "high-protein"],
    visibility: "PUBLIC",
    author: "alex",
  },
  {
    title: "Turkey Chili",
    description: "A big batch of lean, meal-prep-friendly chili loaded with fiber and protein.",
    ingredients: [
      { name: "Ground turkey", quantity: "500 g" },
      { name: "Kidney beans", quantity: "1 can" },
      { name: "Crushed tomatoes", quantity: "1 can" },
      { name: "Onion", quantity: "1" },
      { name: "Chili powder, cumin, paprika", quantity: "to taste" },
    ],
    instructions:
      "Brown the turkey with diced onion. Add beans, tomatoes, and spices. Simmer 25-30 minutes, stirring occasionally.",
    calories: 410,
    proteinG: 35,
    carbsG: 38,
    fatG: 12,
    servings: 4,
    prepMinutes: 40,
    tags: ["dinner", "high-protein", "meal-prep"],
    visibility: "PUBLIC",
    author: "alex",
  },
  {
    title: "Greek Yogurt Protein Parfait",
    description: "A two-minute high-protein breakfast or snack with almost no cleanup.",
    ingredients: [
      { name: "Greek yogurt", quantity: "200 g" },
      { name: "Granola", quantity: "30 g" },
      { name: "Mixed berries", quantity: "80 g" },
      { name: "Honey", quantity: "1 tsp" },
    ],
    instructions: "Layer yogurt, granola, and berries in a glass. Drizzle with honey and serve immediately.",
    calories: 280,
    proteinG: 24,
    carbsG: 30,
    fatG: 6,
    servings: 1,
    prepMinutes: 3,
    tags: ["breakfast", "snack", "quick", "vegetarian"],
    visibility: "PUBLIC",
    author: "demo",
  },
  {
    title: "Veggie Stir-Fry with Tofu",
    description: "A fully plant-based dinner that still delivers a solid protein count.",
    ingredients: [
      { name: "Firm tofu", quantity: "200 g" },
      { name: "Mixed stir-fry vegetables", quantity: "300 g" },
      { name: "Soy sauce", quantity: "2 tbsp" },
      { name: "Sesame oil", quantity: "1 tsp" },
      { name: "Cooked rice noodles", quantity: "150 g" },
    ],
    instructions:
      "Pan-fry cubed tofu until golden. Add vegetables and stir-fry 5 minutes. Toss in noodles and soy sauce, cook 2 more minutes.",
    calories: 380,
    proteinG: 22,
    carbsG: 45,
    fatG: 12,
    servings: 1,
    prepMinutes: 20,
    tags: ["dinner", "vegan", "quick"],
    visibility: "PUBLIC",
    author: "alex",
  },
  {
    title: "Egg White Veggie Omelet",
    description: "Lean and filling, with almost all its calories coming from protein.",
    ingredients: [
      { name: "Egg whites", quantity: "6" },
      { name: "Spinach", quantity: "40 g" },
      { name: "Bell pepper", quantity: "1/2" },
      { name: "Feta cheese", quantity: "20 g" },
    ],
    instructions: "Whisk egg whites and pour into a hot non-stick pan. Add vegetables and cheese, fold, and cook until set.",
    calories: 260,
    proteinG: 28,
    carbsG: 8,
    fatG: 12,
    servings: 1,
    prepMinutes: 10,
    tags: ["breakfast", "high-protein", "quick"],
    visibility: "PRIVATE",
    author: "demo",
  },
  {
    title: "Peanut Butter Banana Protein Shake",
    description: "A calorie-dense shake for lifters who struggle to hit their bulking targets.",
    ingredients: [
      { name: "Banana", quantity: "1" },
      { name: "Peanut butter", quantity: "1 tbsp" },
      { name: "Whey protein", quantity: "1 scoop" },
      { name: "Milk", quantity: "300 ml" },
    ],
    instructions: "Blend all ingredients until smooth and creamy.",
    calories: 350,
    proteinG: 25,
    carbsG: 42,
    fatG: 10,
    servings: 1,
    prepMinutes: 5,
    tags: ["snack", "post-workout", "quick", "vegetarian"],
    visibility: "FRIENDS",
    author: "alex",
  },
  {
    title: "Beef & Broccoli",
    description: "A takeout favorite made lean, with a much better macro split.",
    ingredients: [
      { name: "Lean beef strips", quantity: "200 g" },
      { name: "Broccoli", quantity: "200 g" },
      { name: "Soy sauce", quantity: "2 tbsp" },
      { name: "Garlic and ginger", quantity: "1 tsp each" },
      { name: "Cornstarch", quantity: "1 tsp" },
    ],
    instructions:
      "Sear beef strips over high heat. Add garlic, ginger, and broccoli, stir-fry 3-4 minutes. Add soy sauce mixed with cornstarch to thicken.",
    calories: 500,
    proteinG: 40,
    carbsG: 25,
    fatG: 24,
    servings: 1,
    prepMinutes: 20,
    tags: ["dinner", "high-protein"],
    visibility: "PUBLIC",
    author: "demo",
  },
  {
    title: "Quinoa Chickpea Salad",
    description: "A cold, meal-prep-friendly salad that's entirely plant-based.",
    ingredients: [
      { name: "Cooked quinoa", quantity: "150 g" },
      { name: "Chickpeas", quantity: "150 g" },
      { name: "Cucumber", quantity: "1/2" },
      { name: "Cherry tomatoes", quantity: "100 g" },
      { name: "Lemon vinaigrette", quantity: "2 tbsp" },
    ],
    instructions: "Toss all ingredients together in a bowl with the vinaigrette. Chill before serving.",
    calories: 420,
    proteinG: 18,
    carbsG: 60,
    fatG: 12,
    servings: 2,
    prepMinutes: 15,
    tags: ["lunch", "vegan", "meal-prep"],
    visibility: "PUBLIC",
    author: "alex",
  },
  {
    title: "Cottage Cheese with Berries",
    description: "One of the highest protein-per-calorie snacks you can make in under a minute.",
    ingredients: [
      { name: "Cottage cheese", quantity: "200 g" },
      { name: "Mixed berries", quantity: "80 g" },
      { name: "Cinnamon", quantity: "a pinch" },
    ],
    instructions: "Spoon cottage cheese into a bowl, top with berries and a dash of cinnamon.",
    calories: 220,
    proteinG: 26,
    carbsG: 18,
    fatG: 4,
    servings: 1,
    prepMinutes: 2,
    tags: ["snack", "high-protein", "quick", "vegetarian"],
    visibility: "PUBLIC",
    author: "demo",
  },
];
